// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmtU4tC-6Q5_HX2GW8W4zSsGMPYMKsKLU',
    appId: '1:275776191085:web:0b59c5c4e4a8b7428e1d64',
    messagingSenderId: '275776191085',
    projectId: 'new-chatx-dbddf',
    authDomain: 'new-chatx-dbddf.firebaseapp.com',
    storageBucket: 'new-chatx-dbddf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_AFhKg7u7O5dWlSb4mDxPvLRROV8M6JE',
    appId: '1:275776191085:android:46df6b2d93ca51e98e1d64',
    messagingSenderId: '275776191085',
    projectId: 'new-chatx-dbddf',
    storageBucket: 'new-chatx-dbddf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7qQIywQYAPDOJYMigca7sUpR8e1YFZ7I',
    appId: '1:275776191085:ios:f42a5ccf057fe3f48e1d64',
    messagingSenderId: '275776191085',
    projectId: 'new-chatx-dbddf',
    storageBucket: 'new-chatx-dbddf.appspot.com',
    iosClientId: '275776191085-6ovh31p6t0fh7ga47jftrlhl6ei9hqdd.apps.googleusercontent.com',
    iosBundleId: 'com.xyndev.newChatx',
  );
}
